#!/usr/bin/env bash
# Bash script that generates a MySQL dump 

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

#mysqldump -u root --password="$1" --all-databases > backup.sql
sudo mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
