#!/usr/bin/env bash
# Bash script that generates a MySQL dump 

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

sudo mysqldump -u root -p "$1" --all-databases > backup.sql
tar -czvf "$file_name" backup.sql
